site_name: Desenvolupament web en entorn de Servidor
site_url: https://cipfpbatoi.github.io/dwes2526/
use_directory_urls: false
nav:
  - "Inicio": "index.md"
  - "1.- Arquitectures Web": "01arquitecturas.md"
  - "2.- Programació web amb PHP": "02php.md"
  - "3.- Arquitectura MVC amb Laravel": "03MVC_Laravel.md"
  - "4.- Accés segur i estructurat a bases de dades amb Laravel": "04dades_Laravel.md"
  - "5.- Aplicacions segures i reactives en Laravel": "05seguretat_Laravel.md"
  - "6a.- Desenvolupament d'APIs REST amb Laravel": "06Rest_Laravel.md"
  - "6b.- Desenvolupament d'APIs REST amb Node.js": "06Nodejs.md"
theme:
  language: ca
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    - scheme: default
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Canviar a mode nit
    - scheme: slate 
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Canviar a mode dia
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logofp.png"
  features:
    - header.autohide
    - toc.integrate
    - content.tabs.link
    # - navigation.tabs
    # - navigation.top

extra:
  search:
    language: "ca"
  social:
    - icon: material/twitter
      link: https://twitter.com/aitormedrano
    - icon: material/email-edit
      link: mailto:<a.medrano@edu.gva.es>
  analytics:
    provider: google
    property: G-X6D0LR7TC8

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2021-2026 Aitor Medrano, Luis Alemañ, Ignasi Gomis - Licencia CC BY-NC-SA
